name: CI - Data Wrangler Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ”§ Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: ğŸ’¼ Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: ğŸ“¦ Instalar dependÃªncias com Poetry
        run: poetry install --all-extras

      - name: ğŸ›  Rodar tarefa de checagem
        run: poetry run task check

      - name: Rodar testes
        run: poetry run task test
